//! Shared rule-validation helpers.
//!
//! Split out from the original monolithic `rule.rs` (Phase B1). All
//! items are crate-private; the only entry points that escape the rule
//! module subtree are `validate_http_route` (consumed by `Rule::validate_l7`)
//! and `is_valid_dns_hostname` (consumed by `TargetHost::FromStr`).

use crate::error::{Error, Result};

use super::cert_source::{AcmeChallenge, CertSource};
use super::http_route::HttpRoute;

/// Validate a single [`HttpRoute`] block belonging to `rule_name`.
///
/// Checks:
/// * `hostname` non-empty and a syntactically valid DNS label sequence.
/// * `target` scheme is exactly `"http"`; host and explicit port present.
/// * `cert = Path(_)` requires `key = Some(_)`; XOR.
/// * `cert = Ephemeral` restricts `hostname` to local-only patterns
///   (`localhost`, `*.localhost`, `*.local`).
/// * `key` set without a `Path` `cert` is rejected.
/// * `cert = None` (cert-less route) is permitted. Cert-less routes live
///   only on the per-IP companion listener's plaintext `:80` path; the
///   HTTPS frontend skips them at SNI resolution. `hsts` on a cert-less
///   route is rejected (HSTS over plain HTTP is undefined per RFC 6797).
pub(super) fn validate_http_route(rule_name: &str, route: &HttpRoute) -> Result<()> {
    if route.hostname.is_empty() {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route hostname is empty",
            rule_name
        )));
    }
    if !is_valid_dns_hostname(&route.hostname) {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route hostname {:?} is not a valid DNS name",
            rule_name, route.hostname
        )));
    }

    if route.target.scheme() != "http" {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route {:?}: target URL scheme must be \"http\" \
             (got {:?})",
            rule_name,
            route.hostname,
            route.target.scheme()
        )));
    }
    if route.target.host_str().is_none() {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route {:?}: target URL is missing a host",
            rule_name, route.hostname
        )));
    }
    if route.target.port_or_known_default().is_none() {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route {:?}: target URL has no port and no known \
             default for its scheme",
            rule_name, route.hostname
        )));
    }

    match (&route.cert, &route.key) {
        (Some(CertSource::Path(_)), None) => {
            return Err(Error::InvalidRule(format!(
                "rule {:?}: route {:?}: cert is a file path; `key` must also \
                 be supplied",
                rule_name, route.hostname
            )));
        }
        (Some(CertSource::Ephemeral), Some(_)) => {
            return Err(Error::InvalidRule(format!(
                "rule {:?}: route {:?}: cert = \"ephemeral\" does not take a \
                 separate `key` (the keypair is generated in-process)",
                rule_name, route.hostname
            )));
        }
        (Some(CertSource::Acme(_)), Some(_)) => {
            return Err(Error::InvalidRule(format!(
                "rule {:?}: route {:?}: cert = \"acme\" does not take a \
                 separate `key` (the keypair is generated by the ACME flow)",
                rule_name, route.hostname
            )));
        }
        (None, Some(_)) => {
            return Err(Error::InvalidRule(format!(
                "rule {:?}: route {:?}: `key` is set but no `cert` is \
                 provided",
                rule_name, route.hostname
            )));
        }
        _ => {}
    }

    // HSTS on a cert-less route makes no sense — the only path that
    // serves the route is plain HTTP on :80, and Strict-Transport-Security
    // over HTTP is undefined (browsers ignore the header from non-secure
    // origins per the HSTS RFC). Reject explicitly so operators don't
    // silently lose the header they thought they were setting.
    if route.cert.is_none() && route.hsts.is_some() {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route {:?}: `hsts` requires a cert source — \
             cert-less routes are served as plain HTTP on :80, where HSTS \
             headers are undefined / ignored by browsers",
            rule_name, route.hostname
        )));
    }

    if matches!(route.cert, Some(CertSource::Ephemeral)) && !is_local_only_hostname(&route.hostname)
    {
        return Err(Error::InvalidRule(format!(
            "rule {:?}: route {:?}: cert = \"ephemeral\" is only allowed for \
             `localhost`, `*.localhost`, or `*.local` hostnames",
            rule_name, route.hostname
        )));
    }

    if let Some(CertSource::Acme(acme)) = &route.cert {
        // ACME issuance requires a publicly-resolvable hostname (or for
        // DNS-01: at least a zone the operator controls). Local-only
        // names will never validate; reject early so operators don't
        // hit an opaque "challenge timeout" later.
        if is_local_only_hostname(&route.hostname) {
            return Err(Error::InvalidRule(format!(
                "rule {:?}: route {:?}: cert = \"acme\" is incompatible \
                 with local-only hostnames (`localhost`, `*.localhost`, \
                 `*.local`); use cert = \"ephemeral\" instead",
                rule_name, route.hostname
            )));
        }
        match acme.challenge {
            AcmeChallenge::Http01 => {
                if acme.provider.is_some() {
                    return Err(Error::InvalidRule(format!(
                        "rule {:?}: route {:?}: cert.acme.provider is only \
                         meaningful for challenge = \"dns01\"",
                        rule_name, route.hostname
                    )));
                }
            }
            AcmeChallenge::Dns01 => {
                if acme.provider.as_deref().map(str::is_empty).unwrap_or(true) {
                    return Err(Error::InvalidRule(format!(
                        "rule {:?}: route {:?}: cert.acme.challenge = \"dns01\" \
                         requires `provider = \"<name>\"`",
                        rule_name, route.hostname
                    )));
                }
            }
        }
    }

    Ok(())
}

/// Loose RFC-1123 DNS-name validator. Accepts:
/// * length 1..=253 octets total;
/// * labels of length 1..=63;
/// * labels matching `[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?`;
/// * a single optional trailing dot.
///
/// Wildcard (`*.example.com`) and underscore labels are rejected: a route
/// hostname must be a concrete DNS name, not a pattern. (Per-hostname
/// SNI/Host matching is exact at runtime.)
pub(super) fn is_valid_dns_hostname(s: &str) -> bool {
    let s = s.strip_suffix('.').unwrap_or(s);
    if s.is_empty() || s.len() > 253 {
        return false;
    }
    s.split('.').all(|label| {
        if label.is_empty() || label.len() > 63 {
            return false;
        }
        let bytes = label.as_bytes();
        if !bytes[0].is_ascii_alphanumeric() || !bytes[bytes.len() - 1].is_ascii_alphanumeric() {
            return false;
        }
        bytes
            .iter()
            .all(|&b| b.is_ascii_alphanumeric() || b == b'-')
    })
}

/// True if `host` is one of the allowed `cert = "ephemeral"` hostnames:
/// `localhost`, anything ending in `.localhost`, or anything ending in
/// `.local` (the mDNS suffix; common on home LANs).
fn is_local_only_hostname(host: &str) -> bool {
    let h = host.to_ascii_lowercase();
    let h = h.strip_suffix('.').unwrap_or(&h);
    h == "localhost" || h.ends_with(".localhost") || h.ends_with(".local")
}
