//! Authenticated session layer (Noise_IK over UDP) with strict-monotonic replay protection.
//!
//! High-level shape:
//!
//! * [`StaticKeyPair`] — long-term X25519 identity. Generated by
//!   `yggdrasilctl identity rotate` and persisted to disk as 64 raw
//!   bytes (32-byte secret followed by 32-byte public).
//! * [`Initiator::start`] — dial-side. Produces a `Handshake1` packet and
//!   pending state, which becomes a [`Session`] after consuming `Handshake2`.
//! * [`Responder::process_handshake_1`] — accept-side. Returns a
//!   [`HalfHandshake`] that exposes the *claimed* peer public key so the caller
//!   can authorise (configured peer vs TOFU staging) before completing to a
//!   [`Session`] + `Handshake2` packet.
//! * [`Session`] — established transport state. Owns the AEAD nonces and a
//!   strict-monotonic `last_seen_counter` for replay protection.
//!
//! Replay protection: the cleartext per-packet counter must be **strictly
//! greater** than `last_seen_counter`. Equal or lower values are rejected with
//! [`Error::Replay`]. This is intentionally simpler than a sliding window —
//! the dial-side emits heartbeats at a known cadence, so out-of-order arrival
//! is rare; we trade a small false-rejection rate on UDP reordering for code
//! that is much easier to audit.

use std::path::Path;

use zeroize::Zeroizing;

use crate::error::{Error, Result};
use crate::wire::{self, PacketType, PacketView, SessionId};
use crate::control_frame::{ControlAck, ControlEnvelope};

/// Standard Noise pattern string used by all yggdrasil heartbeat peers.
pub const NOISE_PATTERN: &str = "Noise_IK_25519_ChaChaPoly_BLAKE2s";

/// Length in bytes of a Curve25519 public key.
pub const PUBLIC_KEY_LEN: usize = 32;
/// Length in bytes of a Curve25519 secret key.
pub const SECRET_KEY_LEN: usize = 32;
/// Length in bytes of an identity-file on disk (secret ++ public).
pub const IDENTITY_FILE_LEN: usize = SECRET_KEY_LEN + PUBLIC_KEY_LEN;

/// A long-lived X25519 keypair. Secret bytes are zeroized on drop.
#[derive(Clone)]
pub struct StaticKeyPair {
    secret: Zeroizing<[u8; SECRET_KEY_LEN]>,
    public: [u8; PUBLIC_KEY_LEN],
}

impl std::fmt::Debug for StaticKeyPair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("StaticKeyPair")
            .field("public", &hex::encode(self.public))
            .field("secret", &"<redacted>")
            .finish()
    }
}

impl StaticKeyPair {
    /// Generate a fresh keypair via snow's default resolver.
    pub fn generate() -> Result<Self> {
        let params: snow::params::NoiseParams =
            NOISE_PATTERN.parse().expect("valid noise pattern");
        let kp = snow::Builder::new(params).generate_keypair()?;
        debug_assert_eq!(kp.private.len(), SECRET_KEY_LEN);
        debug_assert_eq!(kp.public.len(), PUBLIC_KEY_LEN);

        let mut secret = [0u8; SECRET_KEY_LEN];
        secret.copy_from_slice(&kp.private);
        let mut public = [0u8; PUBLIC_KEY_LEN];
        public.copy_from_slice(&kp.public);
        Ok(Self {
            secret: Zeroizing::new(secret),
            public,
        })
    }

    /// Construct from raw bytes. Caller must ensure these came from
    /// [`StaticKeyPair::generate`] (or are otherwise a valid X25519 pair).
    pub fn from_raw(secret: [u8; SECRET_KEY_LEN], public: [u8; PUBLIC_KEY_LEN]) -> Self {
        Self {
            secret: Zeroizing::new(secret),
            public,
        }
    }

    /// Decode from the on-disk identity-file layout (`secret` ++ `public`).
    pub fn from_identity_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.len() != IDENTITY_FILE_LEN {
            return Err(Error::Auth("identity file has wrong length"));
        }
        let mut secret = [0u8; SECRET_KEY_LEN];
        let mut public = [0u8; PUBLIC_KEY_LEN];
        secret.copy_from_slice(&bytes[..SECRET_KEY_LEN]);
        public.copy_from_slice(&bytes[SECRET_KEY_LEN..]);
        Ok(Self::from_raw(secret, public))
    }

    /// Serialise to the on-disk identity-file layout.
    pub fn to_identity_bytes(&self) -> [u8; IDENTITY_FILE_LEN] {
        let mut out = [0u8; IDENTITY_FILE_LEN];
        out[..SECRET_KEY_LEN].copy_from_slice(&*self.secret);
        out[SECRET_KEY_LEN..].copy_from_slice(&self.public);
        out
    }

    /// Read an identity file from disk.
    pub fn load_from_file(path: &Path) -> Result<Self> {
        let bytes = std::fs::read(path).map_err(|source| Error::ReadFile {
            path:   path.to_path_buf(),
            source,
        })?;
        Self::from_identity_bytes(&bytes)
    }

    /// Write the identity file to disk with mode `0600`.
    pub fn save_to_file(&self, path: &Path) -> Result<()> {
        use std::io::Write;

        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent).map_err(|source| Error::WriteFile {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }
        }

        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.mode(0o600);
        }
        let mut f = opts.open(path).map_err(|source| Error::WriteFile {
            path: path.to_path_buf(),
            source,
        })?;
        f.write_all(&self.to_identity_bytes()).map_err(|source| Error::WriteFile {
            path: path.to_path_buf(),
            source,
        })?;
        Ok(())
    }

    pub fn public_key(&self) -> &[u8; PUBLIC_KEY_LEN] {
        &self.public
    }

    pub fn secret_bytes(&self) -> &[u8; SECRET_KEY_LEN] {
        &self.secret
    }

    /// Short fingerprint suitable for human display (BLAKE2s-128 of the public
    /// key, rendered as 32 hex characters).
    pub fn fingerprint(&self) -> String {
        public_key_fingerprint(&self.public)
    }
}

/// Compute the short fingerprint of a public key for TOFU display.
pub fn public_key_fingerprint(public: &[u8; PUBLIC_KEY_LEN]) -> String {
    use blake2::digest::{consts::U16, Digest};
    type Blake2s128 = blake2::Blake2s<U16>;
    let mut hasher = Blake2s128::new();
    hasher.update(public);
    let out = hasher.finalize();
    hex::encode(out)
}

fn noise_params() -> snow::params::NoiseParams {
    NOISE_PATTERN.parse().expect("valid noise pattern")
}

// ---- Initiator (dial-side) ----

/// Initiator-side handshake state. Lives only until the responder's
/// `Handshake2` is consumed, at which point it becomes a [`Session`].
#[derive(Debug)]
pub struct Initiator {
    inner:      snow::HandshakeState,
    session_id: SessionId,
}

impl Initiator {
    /// Start a new handshake. Returns the initiator state plus the `Handshake1`
    /// packet to send to yggdrasil.
    pub fn start(
        local: &StaticKeyPair,
        remote_public: &[u8; PUBLIC_KEY_LEN],
        session_id: SessionId,
    ) -> Result<(Self, Vec<u8>)> {
        let mut inner = snow::Builder::new(noise_params())
            .local_private_key(local.secret_bytes())
            .remote_public_key(remote_public)
            .build_initiator()?;

        // Noise_IK msg 1: `e, es, s, ss` — up to ~96 bytes incl. tags for empty payload.
        let mut noise_buf = [0u8; 256];
        let len = inner.write_message(&[], &mut noise_buf)?;

        let mut packet = Vec::with_capacity(wire::PREAMBLE_LEN + len);
        wire::write_preamble(&mut packet, PacketType::Handshake1, session_id);
        packet.extend_from_slice(&noise_buf[..len]);

        Ok((Self { inner, session_id }, packet))
    }

    /// Consume the responder's `Handshake2` packet and finalise the session.
    pub fn complete(mut self, view: &PacketView<'_>) -> Result<Session> {
        if view.packet_type != PacketType::Handshake2 {
            return Err(Error::Auth("expected Handshake2"));
        }
        if view.session_id != self.session_id {
            return Err(Error::Auth("Handshake2 session id mismatch"));
        }
        let mut payload_buf = [0u8; 256];
        self.inner.read_message(view.body, &mut payload_buf)?;
        if !self.inner.is_handshake_finished() {
            return Err(Error::Auth("handshake unexpectedly incomplete"));
        }
        let transport = self.inner.into_transport_mode()?;
        Ok(Session {
            transport,
            session_id: self.session_id,
            last_seen_counter: None,
        })
    }
}

// ---- Responder (yggdrasil) ----

/// Responder-side handshake utilities. Stateless; the half-handshake itself
/// carries all in-progress state.
#[derive(Debug)]
pub struct Responder;

impl Responder {
    /// Process an inbound `Handshake1` packet. The returned [`HalfHandshake`]
    /// exposes the peer's claimed public key so the caller can authorise it
    /// before completing the handshake.
    pub fn process_handshake_1(
        local: &StaticKeyPair,
        view: &PacketView<'_>,
    ) -> Result<HalfHandshake> {
        if view.packet_type != PacketType::Handshake1 {
            return Err(Error::Auth("expected Handshake1"));
        }
        let mut inner = snow::Builder::new(noise_params())
            .local_private_key(local.secret_bytes())
            .build_responder()?;

        let mut payload_buf = [0u8; 256];
        inner.read_message(view.body, &mut payload_buf)?;

        let remote_static = inner
            .get_remote_static()
            .ok_or(Error::Auth("Handshake1 carried no static key"))?;
        if remote_static.len() != PUBLIC_KEY_LEN {
            return Err(Error::Auth("remote static key has wrong length"));
        }
        let mut remote = [0u8; PUBLIC_KEY_LEN];
        remote.copy_from_slice(remote_static);

        Ok(HalfHandshake {
            inner,
            session_id: view.session_id,
            remote_public: remote,
        })
    }
}

/// A responder-side handshake that has read `Handshake1` but not yet written
/// `Handshake2`. Allows the caller to inspect the claimed peer pubkey before
/// committing.
#[derive(Debug)]
pub struct HalfHandshake {
    inner:         snow::HandshakeState,
    session_id:    SessionId,
    remote_public: [u8; PUBLIC_KEY_LEN],
}

impl HalfHandshake {
    pub fn session_id(&self) -> SessionId {
        self.session_id
    }

    /// The peer's static public key as learned from `Handshake1`. Caller should
    /// compare this against the enrolled peer pubkey (or stage for TOFU) before
    /// calling [`HalfHandshake::complete`].
    pub fn remote_public(&self) -> &[u8; PUBLIC_KEY_LEN] {
        &self.remote_public
    }

    /// Short fingerprint of the remote public key for human display.
    pub fn remote_fingerprint(&self) -> String {
        public_key_fingerprint(&self.remote_public)
    }

    /// Write `Handshake2` and transition to the transport session.
    pub fn complete(mut self) -> Result<(Session, Vec<u8>)> {
        let mut noise_buf = [0u8; 256];
        let len = self.inner.write_message(&[], &mut noise_buf)?;
        if !self.inner.is_handshake_finished() {
            return Err(Error::Auth("handshake unexpectedly incomplete after msg 2"));
        }

        let mut packet = Vec::with_capacity(wire::PREAMBLE_LEN + len);
        wire::write_preamble(&mut packet, PacketType::Handshake2, self.session_id);
        packet.extend_from_slice(&noise_buf[..len]);

        let transport = self.inner.into_transport_mode()?;
        Ok((
            Session {
                transport,
                session_id: self.session_id,
                last_seen_counter: None,
            },
            packet,
        ))
    }
}

// ---- Established session ----

/// An established Noise transport session. Bidirectional; can encrypt outbound
/// and decrypt inbound packets independently using snow's per-direction nonces.
#[derive(Debug)]
pub struct Session {
    transport:         snow::TransportState,
    session_id:        SessionId,
    /// Highest received counter seen on this session. `None` = no packet received yet.
    last_seen_counter: Option<u64>,
}

/// Decrypted `Heartbeat` payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecodedHeartbeat {
    pub counter:      u64,
    pub timestamp_ms: u64,
    pub flags:        u8,
}

/// Decrypted `HeartbeatAck` payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecodedHeartbeatAck {
    pub counter:        u64,
    pub echoed_counter: u64,
    pub server_ts_ms:   u64,
}

impl Session {
    pub fn id(&self) -> SessionId {
        self.session_id
    }

    pub fn last_seen_counter(&self) -> Option<u64> {
        self.last_seen_counter
    }

    pub fn sending_counter(&self) -> u64 {
        self.transport.sending_nonce()
    }

    /// Encode an outbound `Heartbeat`. Returns the counter that was used as the
    /// AEAD nonce alongside the wire packet.
    pub fn encode_heartbeat(&mut self, timestamp_ms: u64, flags: u8) -> Result<(u64, Vec<u8>)> {
        let counter = self.transport.sending_nonce();
        let plaintext = wire::encode_heartbeat_plaintext(timestamp_ms, flags);
        self.encode_packet(PacketType::Heartbeat, counter, &plaintext)
            .map(|p| (counter, p))
    }

    /// Encode an outbound `HeartbeatAck`. Returns the counter alongside the wire packet.
    pub fn encode_heartbeat_ack(
        &mut self,
        echoed_counter: u64,
        server_ts_ms: u64,
    ) -> Result<(u64, Vec<u8>)> {
        let counter = self.transport.sending_nonce();
        let plaintext = wire::encode_heartbeat_ack_plaintext(echoed_counter, server_ts_ms);
        self.encode_packet(PacketType::HeartbeatAck, counter, &plaintext)
            .map(|p| (counter, p))
    }

    /// Encode an outbound `Rekey` signal (empty payload).
    pub fn encode_rekey(&mut self) -> Result<(u64, Vec<u8>)> {
        let counter = self.transport.sending_nonce();
        self.encode_packet(PacketType::Rekey, counter, &[])
            .map(|p| (counter, p))
    }

    /// Decode an inbound `Heartbeat`. Replay-rejects if the counter is not
    /// strictly greater than the last accepted counter.
    pub fn decode_heartbeat(&mut self, view: &PacketView<'_>) -> Result<DecodedHeartbeat> {
        let plaintext = self.decode_packet(PacketType::Heartbeat, view)?;
        let (timestamp_ms, flags) = wire::decode_heartbeat_plaintext(&plaintext)?;
        Ok(DecodedHeartbeat {
            counter: view.counter.expect("verified by decode_packet"),
            timestamp_ms,
            flags,
        })
    }

    /// Decode an inbound `HeartbeatAck`.
    pub fn decode_heartbeat_ack(&mut self, view: &PacketView<'_>) -> Result<DecodedHeartbeatAck> {
        let plaintext = self.decode_packet(PacketType::HeartbeatAck, view)?;
        let (echoed_counter, server_ts_ms) = wire::decode_heartbeat_ack_plaintext(&plaintext)?;
        Ok(DecodedHeartbeatAck {
            counter: view.counter.expect("verified by decode_packet"),
            echoed_counter,
            server_ts_ms,
        })
    }

    /// Decode an inbound `Rekey` signal. Empty plaintext.
    pub fn decode_rekey(&mut self, view: &PacketView<'_>) -> Result<u64> {
        let plaintext = self.decode_packet(PacketType::Rekey, view)?;
        if !plaintext.is_empty() {
            return Err(Error::MalformedPacket("rekey payload must be empty"));
        }
        Ok(view.counter.expect("verified by decode_packet"))
    }

    /// Encode an outbound `Control` packet carrying a postcard-encoded
    /// [`ControlEnvelope`] inside Noise AEAD.
    pub fn encode_control(&mut self, envelope: &ControlEnvelope) -> Result<(u64, Vec<u8>)> {
        let counter = self.transport.sending_nonce();
        let plaintext = postcard::to_allocvec(envelope)?;
        self.encode_packet(PacketType::Control, counter, &plaintext)
            .map(|p| (counter, p))
    }

    /// Encode an outbound `ControlAck` packet carrying a postcard-encoded
    /// [`ControlAck`] inside Noise AEAD.
    pub fn encode_control_ack(&mut self, ack: &ControlAck) -> Result<(u64, Vec<u8>)> {
        let counter = self.transport.sending_nonce();
        let plaintext = postcard::to_allocvec(ack)?;
        self.encode_packet(PacketType::ControlAck, counter, &plaintext)
            .map(|p| (counter, p))
    }

    /// Decode an inbound `Control` packet into its envelope. Replay-rejects
    /// like every post-handshake packet.
    pub fn decode_control(&mut self, view: &PacketView<'_>) -> Result<ControlEnvelope> {
        let plaintext = self.decode_packet(PacketType::Control, view)?;
        postcard::from_bytes::<ControlEnvelope>(&plaintext).map_err(Error::from)
    }

    /// Decode an inbound `ControlAck` packet into its envelope.
    pub fn decode_control_ack(&mut self, view: &PacketView<'_>) -> Result<ControlAck> {
        let plaintext = self.decode_packet(PacketType::ControlAck, view)?;
        postcard::from_bytes::<ControlAck>(&plaintext).map_err(Error::from)
    }

    // ---- internals ----

    fn encode_packet(
        &mut self,
        packet_type: PacketType,
        counter: u64,
        plaintext: &[u8],
    ) -> Result<Vec<u8>> {
        let mut ct_buf = [0u8; wire::MAX_PACKET_LEN];
        let ct_len = self.transport.write_message(plaintext, &mut ct_buf)?;

        let mut packet =
            Vec::with_capacity(wire::PREAMBLE_LEN + wire::COUNTER_LEN + ct_len);
        wire::write_preamble(&mut packet, packet_type, self.session_id);
        wire::write_counter(&mut packet, counter);
        packet.extend_from_slice(&ct_buf[..ct_len]);
        Ok(packet)
    }

    fn decode_packet(
        &mut self,
        expected: PacketType,
        view: &PacketView<'_>,
    ) -> Result<Vec<u8>> {
        if view.packet_type != expected {
            return Err(Error::Auth("unexpected packet type"));
        }
        if view.session_id != self.session_id {
            return Err(Error::Auth("session id mismatch"));
        }
        let counter = view
            .counter
            .ok_or(Error::MalformedPacket("post-handshake packet missing counter"))?;
        // Strict-monotonic replay protection.
        if let Some(last) = self.last_seen_counter {
            if counter <= last {
                return Err(Error::Replay {
                    counter,
                    last_seen: last,
                });
            }
        }

        // Set snow's receive nonce to match the wire counter, then attempt to decrypt.
        // On failure, snow leaves the recv nonce unchanged; we additionally leave
        // `last_seen_counter` unchanged so attackers cannot ratchet it forward.
        self.transport.set_receiving_nonce(counter);
        let mut pt_buf = [0u8; wire::MAX_PACKET_LEN];
        let pt_len = self.transport.read_message(view.body, &mut pt_buf)?;
        self.last_seen_counter = Some(counter);
        Ok(pt_buf[..pt_len].to_vec())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_pair() -> (StaticKeyPair, StaticKeyPair) {
        (
            StaticKeyPair::generate().unwrap(),
            StaticKeyPair::generate().unwrap(),
        )
    }

    /// Helper: drive a full handshake, return (initiator_session, responder_session).
    fn establish() -> (Session, Session, StaticKeyPair, StaticKeyPair) {
        let (initiator_kp, responder_kp) = make_pair();
        let sid = SessionId([1, 2, 3, 4]);
        let (initiator, hs1) =
            Initiator::start(&initiator_kp, responder_kp.public_key(), sid).unwrap();
        let view1 = wire::parse(&hs1).unwrap();
        let half = Responder::process_handshake_1(&responder_kp, &view1).unwrap();
        assert_eq!(half.remote_public(), initiator_kp.public_key());
        let (resp_session, hs2) = half.complete().unwrap();
        let view2 = wire::parse(&hs2).unwrap();
        let init_session = initiator.complete(&view2).unwrap();
        (init_session, resp_session, initiator_kp, responder_kp)
    }

    #[test]
    fn keypair_roundtrip_on_disk_layout() {
        let kp = StaticKeyPair::generate().unwrap();
        let bytes = kp.to_identity_bytes();
        let kp2 = StaticKeyPair::from_identity_bytes(&bytes).unwrap();
        assert_eq!(kp.public_key(), kp2.public_key());
        assert_eq!(kp.secret_bytes(), kp2.secret_bytes());
    }

    #[test]
    fn handshake_roundtrip_and_heartbeat_decrypt() {
        let (mut init, mut resp, _, _) = establish();
        let (counter, packet) = init.encode_heartbeat(42, 0x01).unwrap();
        let view = wire::parse(&packet).unwrap();
        let hb = resp.decode_heartbeat(&view).unwrap();
        assert_eq!(hb.counter, counter);
        assert_eq!(hb.timestamp_ms, 42);
        assert_eq!(hb.flags, 0x01);
    }

    #[test]
    fn ack_path_roundtrip() {
        let (mut init, mut resp, _, _) = establish();
        // Heartbeat first to push counter forward.
        let (counter, hb_packet) = init.encode_heartbeat(100, 0).unwrap();
        let _ = resp.decode_heartbeat(&wire::parse(&hb_packet).unwrap()).unwrap();
        // Now resp acks.
        let (ack_counter, ack_packet) = resp.encode_heartbeat_ack(counter, 200).unwrap();
        let ack = init
            .decode_heartbeat_ack(&wire::parse(&ack_packet).unwrap())
            .unwrap();
        assert_eq!(ack.counter, ack_counter);
        assert_eq!(ack.echoed_counter, counter);
        assert_eq!(ack.server_ts_ms, 200);
    }

    #[test]
    fn replay_is_rejected_strictly() {
        let (mut init, mut resp, _, _) = establish();
        let (_, packet) = init.encode_heartbeat(10, 0).unwrap();
        let _ = resp.decode_heartbeat(&wire::parse(&packet).unwrap()).unwrap();
        // Same packet again: counter is no longer strictly greater.
        let err = resp.decode_heartbeat(&wire::parse(&packet).unwrap()).err();
        assert!(matches!(err, Some(Error::Replay { .. })));
    }

    #[test]
    fn tampered_counter_fails_decryption() {
        let (mut init, mut resp, _, _) = establish();
        let (_, mut packet) = init.encode_heartbeat(7, 0).unwrap();
        // Flip a byte inside the cleartext counter — should make AEAD verify fail.
        let counter_start = wire::PREAMBLE_LEN;
        packet[counter_start + 7] ^= 0x01;
        let err = resp.decode_heartbeat(&wire::parse(&packet).unwrap()).err();
        // After tamper, counter looks "newer" so replay check passes; AEAD then fails.
        assert!(matches!(err, Some(Error::Noise(_))));
    }

    #[test]
    fn wrong_remote_key_rejects_handshake() {
        let (initiator_kp, responder_kp) = make_pair();
        let (_attacker_kp, _) = make_pair();
        let sid = SessionId([9, 9, 9, 9]);
        let (_init, hs1) =
            Initiator::start(&initiator_kp, responder_kp.public_key(), sid).unwrap();
        let view1 = wire::parse(&hs1).unwrap();
        // Try to process with a DIFFERENT responder key (the wrong key for this handshake).
        let wrong_responder = StaticKeyPair::generate().unwrap();
        let err = Responder::process_handshake_1(&wrong_responder, &view1).err();
        assert!(matches!(err, Some(Error::Noise(_))));
    }

    #[test]
    fn fingerprint_is_deterministic_and_short() {
        let kp = StaticKeyPair::from_raw([7u8; 32], [9u8; 32]);
        let fp = kp.fingerprint();
        assert_eq!(fp.len(), 32);
        assert_eq!(fp, public_key_fingerprint(&[9u8; 32]));
    }

    #[test]
    fn session_id_mismatch_on_handshake_2_is_rejected() {
        let (initiator_kp, responder_kp) = make_pair();
        let sid = SessionId([1, 1, 1, 1]);
        let other_sid = SessionId([2, 2, 2, 2]);
        let (initiator, hs1) =
            Initiator::start(&initiator_kp, responder_kp.public_key(), sid).unwrap();
        let view1 = wire::parse(&hs1).unwrap();
        let half = Responder::process_handshake_1(&responder_kp, &view1).unwrap();
        let (_, mut hs2) = half.complete().unwrap();
        // Corrupt the session id in the responder's outbound packet.
        hs2[1..5].copy_from_slice(&other_sid.0);
        let view2 = wire::parse(&hs2).unwrap();
        let err = initiator.complete(&view2).err();
        assert!(matches!(err, Some(Error::Auth(_))));
    }

    #[test]
    fn long_run_of_1000_heartbeats() {
        let (mut init, mut resp, _, _) = establish();
        let mut prev: Option<u64> = None;
        for i in 0..1000u64 {
            let (counter, packet) = init.encode_heartbeat(i, 0).unwrap();
            if let Some(p) = prev {
                assert!(counter > p, "counter must be strictly monotonic");
            }
            prev = Some(counter);
            let hb = resp.decode_heartbeat(&wire::parse(&packet).unwrap()).unwrap();
            assert_eq!(hb.timestamp_ms, i);
            assert_eq!(hb.counter, counter);
        }
        assert!(prev.unwrap() >= 999);
    }

    #[test]
    fn control_envelope_roundtrips_through_session() {
        use crate::control_frame::{ControlBodyType, ControlEnvelope};
        let (mut init, mut resp, _, _) = establish();
        let env = ControlEnvelope {
            seq: 1,
            body_type: ControlBodyType::Noop.as_byte(),
            body: b"hello chain".to_vec(),
        };
        let (counter, packet) = init.encode_control(&env).unwrap();
        let view = wire::parse(&packet).unwrap();
        assert_eq!(view.packet_type, PacketType::Control);
        assert_eq!(view.counter, Some(counter));
        let back = resp.decode_control(&view).unwrap();
        assert_eq!(back, env);
    }

    #[test]
    fn control_ack_roundtrips_through_session() {
        use crate::control_frame::{AckStatus, ControlAck};
        let (mut init, mut resp, _, _) = establish();
        let ack = ControlAck { seq: 99, status: AckStatus::Reject(0xBEEF) };
        let (counter, packet) = resp.encode_control_ack(&ack).unwrap();
        let view = wire::parse(&packet).unwrap();
        assert_eq!(view.packet_type, PacketType::ControlAck);
        assert_eq!(view.counter, Some(counter));
        let back = init.decode_control_ack(&view).unwrap();
        assert_eq!(back, ack);
    }

    #[test]
    fn control_decode_rejects_wrong_packet_type() {
        use crate::control_frame::{AckStatus, ControlAck};
        let (mut init, mut resp, _, _) = establish();
        let ack = ControlAck { seq: 1, status: AckStatus::Ok };
        let (_, packet) = init.encode_control_ack(&ack).unwrap();
        let view = wire::parse(&packet).unwrap();
        // Trying to decode a ControlAck as a Control should fail.
        let err = resp.decode_control(&view).err();
        assert!(matches!(err, Some(Error::Auth(_))));
    }
}
